page({
handleConsole(){
   console.log('我被点了')
},
handleParent(){
  console.log("父亲被点了")
},
handleChildren(){
  console.log("孩子被点了")
},
handleClick01(event){
  console.log(event)
  console.log(event.target.dataset)
  console.log(event.target.dataset.name)
  console.log(event)
}
})